// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCLibIytcTfJqSOYBtSpYS_BF7eIbJz5M',
    appId: '1:991341610790:web:d4f1df0e228e32263363e7',
    messagingSenderId: '991341610790',
    projectId: 'flutterweb-41663',
    authDomain: 'flutterweb-41663.firebaseapp.com',
    storageBucket: 'flutterweb-41663.appspot.com',
    measurementId: 'G-ZDFHKJG4ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDujRCWeOi2vDk2YCrb_0lJ9isr-sVZjOk',
    appId: '1:991341610790:android:18c9a76d99fde03d3363e7',
    messagingSenderId: '991341610790',
    projectId: 'flutterweb-41663',
    storageBucket: 'flutterweb-41663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-W6w_OyBQuwgbu1vWXNAAREjLPmCiusA',
    appId: '1:991341610790:ios:508ec804c699b05c3363e7',
    messagingSenderId: '991341610790',
    projectId: 'flutterweb-41663',
    storageBucket: 'flutterweb-41663.appspot.com',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-W6w_OyBQuwgbu1vWXNAAREjLPmCiusA',
    appId: '1:991341610790:ios:508ec804c699b05c3363e7',
    messagingSenderId: '991341610790',
    projectId: 'flutterweb-41663',
    storageBucket: 'flutterweb-41663.appspot.com',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCLibIytcTfJqSOYBtSpYS_BF7eIbJz5M',
    appId: '1:991341610790:web:aba123c60a74e0343363e7',
    messagingSenderId: '991341610790',
    projectId: 'flutterweb-41663',
    authDomain: 'flutterweb-41663.firebaseapp.com',
    storageBucket: 'flutterweb-41663.appspot.com',
    measurementId: 'G-FS0PZSW2HL',
  );
}
